# Generated by Django 2.1.7 on 2019-05-03 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20190331_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='katilimci',
            field=models.ManyToManyField(blank=True, related_name='katilimcii', to=settings.AUTH_USER_MODEL),
        ),
    ]
