# Generated by Django 2.1.7 on 2019-05-03 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepost',
            name='katilimci',
            field=models.ManyToManyField(blank=True, related_name='katilimci', to=settings.AUTH_USER_MODEL),
        ),
    ]
