# Generated by Django 2.1.7 on 2019-05-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_katilim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katilim',
            name='post',
        ),
        migrations.RemoveField(
            model_name='katilim',
            name='user',
        ),
        migrations.DeleteModel(
            name='Katilim',
        ),
    ]
